# Meta
title: Coughlin Wedding
email: kevintcoughlin+wedding@gmail.com
description: Site for the wedding of Alison Ferro & Kevin Coughlin
baseurl: ""
url: "https://www.ferrocoughlin.com"
twitter_username: kevintcoughlin
github_username:  kevintcoughlin
permalink: pretty
fb_app_id: "413937465645543"

# Build settings
markdown: kramdown
